### PR TITLE
[TRB-40491]:Upload the yaml/script files for deploying t8c-client-operator

### PR DESCRIPTION
**Pull request by kevinwangcn**
This PR includes 1 script file and 3 yaml files, which will be used by the customer for deploying `t8c-client-operator` on a K8s cluster.

### CODE REVIEW

**Comment by kevinwangcn** [comment]
@turbodeploy , I don't know the procedure for using this repo. I just follow the way of using `kubeturbo` . What I want to do is upload a few scripts and yaml files which will be used by the customer for deploying the `t8c-client-operator`.  These files are supposed to be accessed publicly. Could you please tell me the right way to do that?

**Comment by andreiastra** [comment]
Please update the Wiki page accordingly.

**Comment by andreiastra** [comment]
> Why is this going directly in here? Shouldn't this be committed into the xl code base, which would then be placed here after the next release?

Kevin, please sync up on this with Green team: David and Michael.

**Comment by kevinwangcn** [comment]
> Please update the Wiki page accordingly.

The Wiki is internally used.  All of the mentioned filed there should be accessed internally. This is mainly for GA documentation work.

**Pull request closed without merging**
